config/routes.rb
Rails.application.routes.draw do
  resources :earthquakes, only: [:index] do
    get :california_earthquakes, on: :collection, as: :california
    get :top_us_cities_earthquakes, on: :collection, as: :top_us_cities
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'earthquakes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/earthquake.rb
class Earthquake < ApplicationRecord
  validates :usgs_id, presence: true, uniqueness: true
  validates :place, presence: true
  validates :city, presence: true
  validates :happened_at, presence: true
  validates :timezone, presence: true
  validates :magnitude, presence: true, numericality: true

  scope :in, -> (city) { where(city: city) }
  scope :sorted, -> { order(magnitude: :desc) }

  def self.top_us_cities
    cities = Earthquake.select("*, COUNT(city)")
                       .group('city')
                       .order("count(city) desc")
                       .limit(3)
                       .pluck(:city)

    cities.reduce([]) do |acc, current_city|
      acc.concat(Earthquake.in(current_city).sorted)
    end
  end

  def formatted_happened_at
    happened_at.strftime("%Y-%m-%dT%H:%M:%S%:z")
  end
end

app/models/iquake_analyzer.rb
class IquakeAnalyzer

  def initialize
  end

  def list_california_earthquakes
    Earthquake.in('CA').sorted
  end

  def list_top_us_cities_earthquakes
    Earthquake.top_us_cities
  end

  def print_formatted_list(list)
    puts list.map { |item| format_earthquake_record(item) }
  end

  def format_earthquake_record(earthquake)
    [
      earthquake.formatted_happened_at,
      earthquake.place.gsub('CA', 'California'),
      "Magnitude: #{earthquake.magnitude}",
    ].join("\t|\t")
  end
end

app/models/usgs_client.rb
class UsgsClient

  attr_reader :api_uri
  attr_accessor :data

  def initialize
    @api_uri = 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.geojson'
  end

  def fetch_data
    # get data from remote api
    response = Net::HTTP.get(URI(api_uri))
    # parse response
    parser = UsgsClient::DataParser.new(JSON.parse(response))
    self.data = parser.data
  end

  class DataParser
    # from https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php
    attr_accessor :data
    # information we need: id, mag, place, time, tz
    FEATURE_ATTRIBUTES = ['mag', 'place', 'time', 'tz']

    def initialize(json={})
      process_data(json)
    end

    def process_data(json)
      features = json['features'] || []
      self.data = features.map do |feature|
        process_feature(feature)
      end
    end

    def process_feature(feature = {})
      id = feature['id']
      attributes = feature['properties'].slice(*FEATURE_ATTRIBUTES)
      city = get_city_from_place(attributes['place'])
      happened_at = get_utc_date_from_epoc_miliseconds(attributes['time'])

      return {
        usgs_id: id,
        magnitude: attributes['mag'],
        place: attributes['place'],
        city: city,
        happened_at: happened_at,
        timezone: attributes['tz'],
      }
    end

    def get_city_from_place(place)
      place.match(/,\s(.*)$/) { |m| m[1] }
    end

    def get_utc_date_from_epoc_miliseconds(time)
      Time.at(time / 1000.0).utc
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/earthquakes_controller.rb
class EarthquakesController < ApplicationController
  def index
    redirect_to california_earthquakes_path
  end

  def california_earthquakes
    @title = "List all earthquakes in California in the past month, sorted by decreasing magnitude"
    @earthquakes = Earthquake.in('CA').sorted

    render :index
  end

  def top_us_cities_earthquakes
    @title = "List all earthquakes in the top 3 US states (by number of quakes), sorted by state then by decreasing magnitude"
    @earthquakes = Earthquake.top_us_cities

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/earthquakes/_earthquake.html.erb
<tr>
  <td><%= earthquake.formatted_happened_at %></td>
  <td><%= earthquake.place.gsub('CA', 'California') %></td>
  <td>Magnitude: <%= earthquake.magnitude %></td>
</tr>

app/views/earthquakes/index.html.erb
<h1 class="main-title"><%= @title %></h2>

<table class="earthquakes-table table table-sm table-bordered">
  <thead class="thead-dark">
    <th>Date</th>
    <th>Place</th>
    <th>Magnitude</th>
  </thead>
  <tbody>
    <%= render @earthquakes %>
  </tbody>
</table>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">iQuake Analyzer</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(california_earthquakes_path) %>">
        <%= link_to "California earthquakes", california_earthquakes_path, class: 'nav-link' %>
      </li>

      <li class="nav-item <%= 'active' if current_page?(top_us_cities_earthquakes_path) %>">
        <%= link_to "3 top US cities", top_us_cities_earthquakes_path, class: 'nav-link' %>
      </li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>iQuake Analyzier</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>